// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jh123x/prompiler/internal/adapters/source"
	"github.com/Jh123x/prompiler/internal/builtin"
	"github.com/Jh123x/prompiler/internal/domain"
)

// Injectors from wire.go:

// initializeApplication wires the application shell (composition root).
func initializeApplication() (*domain.Application, error) {
	sourceProvider := source.NewFSSource()
	registry := builtin.NewRegistry()
	application := domain.NewApplication(sourceProvider, registry)
	return application, nil
}
